### ISSUE TITLE
OSError: Result too large

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ofalk/libdnet#6]
```
What steps will reproduce the problem?

>>> import dnet
>>> dnet.eth("eth0")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "dnet.pyx", line 112, in dnet.eth.__init__
OSError: Result too large
>>> dnet.eth("eth7")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "dnet.pyx", line 112, in dnet.eth.__init__
OSError: Result too large
>>> dnet.eth(None)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "dnet.pyx", line 110, in dnet.eth.__init__
TypeError: expected string or Unicode object, NoneType found


What is the expected output? What do you see instead?

there is no way to specify that we want the type=6 (ethernet) interface. The 
dnet.eth() method and the underlying eth_open() C function only take 
the plain interface name as arguments.

What version of the product are you using? On what operating system?
Python 2.6.3
dnet 1.12 win32
Windows 7 / Vista

Please provide any additional information below.

>>> import dnet
>>> for iface in dnet.intf(): print iface
...

{'flags': 32, 'type': 1, 'name': 'eth0', 'mtu': 0L}
...
{'flags': 33, 'link_addr': 0a:aa:20:52:41:53, 'type': 6, 'name': 'eth0', 'mtu': 
1500L}
...
{'addr': 192.168.1.99/24, 'mtu': 1500L, 'flags': 33, 'link_addr': 
00:1f:3c:34:1c:0c, 'type': 71, 'name': 'eth0'}
...
```

Original issue reported on code.google.com by `fastian2...@gmail.com` on 31 Jan 2010 at 12:14

**Comment by ofalk** [comment]
old report. closing.
